INHERIT: mkdocs-base.yaml
site_name: "dtpay — Payment Observability Workshop"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/domuharahap/dynatrace-jmeter-enablement"
nav:
  - '1. Introduction': index.md
  - '2. dtpay — Payment Use Case': dtpay.md
  - '3. JMeter Load Tester': jmeter.md
  - '4. Container image': container-image.md
  - '5. Instantiation types': instantiation-types.md
  - '6. Dynatrace integration': dynatrace-integration.md
  - '7. The Framework': framework.md
  - '8. User Experience': user-experience.md
  - "9. Testing": testing.md
  - "10. Functions Reference": functions.md
  - "11. Versioning Policy": versioning.md
  - "12. Resources": resources.md
  - "13. What's next?": whats-next.md
extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/ff78563295ff1e42_complete.js"
