INHERIT: mkdocs-base.yaml
site_name: "EdgeConnect — Automation Workflow Enablement"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/domuharahap/Dynatrace-EdgeConnect"
nav:
  - 'About': index.md
  - 'Getting Started': getting-started.md
  - 'Deployment': edgeconnect-deployment.md
  - 'Use Cases': edgeconnect-usecases.md
  - 'Cleanup': cleanup.md
  - 'Resources': resources.md
  - "What's Next": whats-next.md
extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/ff78563295ff1e42_complete.js"
